#ifndef ERROR_HANDLING_H
#define ERROR_HANDLING_H

typedef enum ERRR_ {
    OK=0,
    CREATE_SOCKET,
    IP_PORT_INVALID,
    SERVER_INVALID,
    COULD_NOT_CONNECT_TO_SERVER,
    BUFFER_INVALID,
    ERROR_WHILE_SENDING,
    COULD_NOT_SEND_ALL_DATA,
    SOCKET_INVALID,
    RECEIVING_FAILED,
    CLOSING_SOCKET_FAILED
} ERRR;

const char* GetErrorMessage(ERRR error);

#endif